version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/python:3.8.10

jobs:
  prep:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Installing numpy
          command: pip3 install numpy==1.22.1

      - run:
          name: Installing scipy
          command: pip3 install scipy==1.8.0

      - run:
          name: Installing matplotlib
          command: pip3 install matplotlib==3.5.1

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  build:
    <<: *defaults
    steps:
      - run:
          name: Testing packages
          command: python3 helloworld.py

  # lint:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo
        
  #     - run:
  #         name: Running linter
  #         command: npm run lint
