version: 2.1
orbs:
  python: circleci/python@2.0.3

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/python:3.8.10

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - v1-dependencies{{ checksum "package.json" }}

      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Installing gh-pages
          command: npm install

      - run: python3 --version

      - run:
          name: Hello World
          command: python3 helloworld.py
      
      - run:
          name: Saving everything
          command: node save_data.js

      - save_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - v1-dependencies{{ checksum "package.json" }}
          paths:
            - "venv"
            - node_modules

      - persist_to_workspace:
          root: ~/repo
          paths: .

  # build:
  #   <<: *defaults
  #   steps:
  #     - checkout

  #     - run:
  #         name: Testing packages
  #         command: python3 helloworld.py

workflows:
  version: 2
  package:
    jobs:
      - build

  # lint:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo
        
  #     - run:
  #         name: Running linter
  #         command: npm run lint
