version: 2.1
orbs:
  python: circleci/python@2.0.3

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/python:3.8.10

jobs:
  install:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - python/install-packages:
          pkg-manager: pip

      # - run:
      #     name: Installing packages
      #     command: pip3 install numpy scipy matplotlib

      - run: python3 --version

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  build:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Testing packages
          command: python3 helloworld.py

workflows:
  version: 2
  package:
    jobs:
      - install
      - build:
          requires:
            - install

  # lint:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo
        
  #     - run:
  #         name: Running linter
  #         command: npm run lint
